// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import FormThrottlerController from "./form_throttler_controller"
application.register("form-throttler", FormThrottlerController)
